name: Sample Plugin
main: com.dinnerbone.bukkit.sample.SamplePlugin
version: 0.5
commands:
  pos:
    description: Displays your position or teleports you to another.
    usage: "Usage: '/pos' to get current position, or '/pos x y z' to teleport to x,y,z"
  debug:
    description: Toggles your debugging status for this plugin.
    usage: /debug